# Travis build file for building the documentation and checking for errors.

sudo: false

language: python

python:
    - "3.6"

install:
    - pip install -r requirements.txt

script:
    - "sphinx-build -qnN docs docs/_build/html"
